import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "../assets/css/responsive.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'aos/dist/aos.css';
import 'animate.css';
import AOSProvider from "./AOSProvider";
import Header from "@/components/Header/page";
import Loader from "@/components/Load/page";
import Footer from "@/components/Footer/page";
// import 'animate.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pivot Path",
  description: "Generated by Pivot Path",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning={true} >
         <Loader />
            <Header />        
              <AOSProvider>
                {children}
              </AOSProvider>
            <Footer />
      </body>
    </html>
  );
}
